### ISSUE TITLE
Describe import process

### ISSUE THREAD

**Issue by mgrauer** [DigitalSlideArchive/NCI-SEER-Pediatric-WSI-Pilot#41]
Provide a description of the import process. I'll sanity check it and add it to the USAGE docs.

**Comment by manthey** [comment]
Assuming that the system has been configured with a mounted import directory, the import process is:
- Files are copied to the local import directory.  They can have any folder structure.  Files consist of
  - excel files (identified by ending in `.xls` or `.xlsx`)
  - image files (anything else except for ignored files)
  - ignored files (to facilitate bulk uploads, we ignore files ending in `.txt`, `.xml`, `.zip`)  [This list can be changed easily]
- From the `Imported` folder (or any sub folder), click on the `Import` button.  A background process starts that scans through the mounted import directory.
  - Each excel file is parsed for a header row that has `TokenID`, `ImageID`, and `ScannedFileName`
  - If there are any excel files that do not have a header row, an error is thrown and no import is performed.
  - If the same `ScannedFileName` is listed in multiple excel files, the newest file is used by preference.
  - The `ScannedFileName` is expected to be just the file name (e.g., no path)
- Images are ingested depending on one of the following categories:
  - present: The image is listed in an excel file and is already in the system based on file path and matching file size.  No action is performed.
  - added: The image is listed in an excel file and is not in the system.  It is added in the Imported directory in the a folder named `TokenID` with a filename `ImageID.<extension>`.
  - replaced: The image is listed in an excel file, is in the system, but has a different file size.  The existing file is removed from the system and readded.
  - missing: The image is listed in an excel file but is not in the import directory.
  - unlisted: The image is not listed in an excel file but is in the import directory.
- When all images are processed, a message is displayed summarizing what images were in each of the five states above (e.g., "Import complete. 19 files added. 1 file missing from import folder")
  - The UI is refreshed.
- All images that are listed in an excel file AND are
