### ISSUE TITLE
Describe export process

### ISSUE THREAD

**Issue by mgrauer** [DigitalSlideArchive/NCI-SEER-Pediatric-WSI-Pilot#42]
Describe the export process, I'll sanity check and then document.

**Comment by manthey** [comment]
In the `Finished` folder, two buttons appear at the top: `Export Recent` and `Export All`.  Click either copies files from the finished folder to the mounted export folder.  Subfolder structure within the Finished folder is maintained.  If a file already exists, it is skipped.   Recent exports are any items in the Finished folder that have not been exported before.  After each export, items are tagged with metadata indicating that they have been exported.

After export, a message is shown indicating how many files were exported, how many were already present and the same size, and how many were already present and differed in size.
